server:
  servlet:
    context-path: /api

spring:
  application:
    name: deliberation-api

  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      display-request-duration: true
    api-docs:
      path: /v3/api-docs
      enabled: true

  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGODB_URI:mongodb://${MONGO_USER:admin}:${MONGO_PASS:admin}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB:deliberationapidb}?authSource=${MONGO_AUTH_DB:admin}}
