server:
  servlet:
    context-path: /api

api:
  base-url: ${BASE_URL:http://localhost:8080/api/v1}


spring:
  application:
    name: deliberation-api

  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      display-request-duration: true
    api-docs:
      path: /v3/api-docs
      enabled: true

  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGODB_URI:mongodb://admin:admin@localhost:27017/deliberationapidb?authSource=admin}
