server:
  servlet:
    context-path: /api

api:
  base-url: ${BASE_URL:http://localhost:8080/api/v1}

mongock:
  migration-scan-package:
    - br.com.deliberation_api.infrastructure.database.migration

logging:
  level:
    io.mongock: DEBUG


spring:
  application:
    name: deliberation-api

  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      display-request-duration: true
    api-docs:
      path: /v3/api-docs
      enabled: true

  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb+srv://application_reder_user:yJ40ZbRZef7zWK4u@deliberationapi.hayornf.mongodb.net/deliberationapidb

